#51 xpbd
IMP-Engine/Engine pull request #54
Opened 2017-03-29 11:25 UTC by Drenata

Merge after restructure branch has been merged

2017-03-30 11:53 UTC, artog requested changes

2017-03-30 11:53 UTC, artog commented on src/constraints/DistanceConstraintData.cpp
> +	float aDash = (stiffness[constraintIndex] / (dt*dt));
`double` to `float` conversion

2017-03-30 12:07 UTC, artog approved these changes

2017-04-04 11:36 UTC, lwestlund approved these changes
I mean, it works, but I can't tell what changed.

2017-05-05 08:07 UTC, Drenata commented
Outdated, see #51 v2 for more updated version

2017-05-05 08:07 UTC, closed without merging